import { authGetSession } from "@/actions/auth/auth.get-session.action";
import { AppConstants } from "@/constants/app.constants";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: `${AppConstants.APP_NAME}-Auth`,
  description: "Generated by vengardus",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resp = await authGetSession();

  if (resp.success && resp.data.isAuthenticated) {
    redirect(AppConstants.URL_HOME);
  }
  return <div className="">{children}</div>;
}
