import { authGetSessionUseCase } from "@/server/modules/auth/use-cases/auth.get-session.use-case";
import { AppConstants } from "@/shared/constants/app.constants";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: `${AppConstants.APP_NAME}-Auth`,
  description: "Generated by vengardus",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resp = await authGetSessionUseCase();

  if (resp.success && resp.data.isAuthenticated) {
    redirect(AppConstants.URL_HOME);
  }
  return <div className="">{children}</div>;
}
