import type { Metadata } from "next";
import { AppConstants } from "@/shared/constants/app.constants";
import Navbar  from "@/components/layout/navbar/navbar.client";
// import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: `${AppConstants.APP_NAME}`,
  description: "Generated by vengardus",
};

export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  console.log("Rendering ROOT Layout")
  return (
    <div className="">
      <Navbar />
      <div className="relative top-16 h-[calc(100vh-64px)] bg-background text-foreground py-2 px-3">
        {children}
      </div>
      {/* <Toaster closeButton richColors  /> */}

    </div>
  );
}
