
import type { Metadata } from "next";
import  Navbar  from "@/components/layout/navbar/navbar.client";
import { Toaster } from "@/components/ui/sonner"

//export const experimental_ppr = true


export const metadata: Metadata = {
  title: "POS - Venta",
  description: "Generated by create next app",
};

export default function FeaturesLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  console.log("Rendering Layout")
  return (
    <div className="">
      <Navbar />
      <div className="relative top-16 h-[calc(100vh-64px)] bg-background text-foreground py-2 px-3 h-screen">
        {children}
      </div>
      <Toaster closeButton richColors  />
    </div>
  );
}
