
import type { Metadata } from "next";
import  Navbar  from "@/components/layout/navbar/navbar.client";
import { Toaster } from "@/components/ui/sonner"

//export const experimental_ppr = true


export const metadata: Metadata = {
  title: "POS - Venta",
  description: "Generated by create next app",
};

export default function FeaturesLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  console.log("Rendering Layout")
  return (
    <div className="flex h-screen flex-col overflow-hidden">
      <Navbar />
      <main className="flex-1 overflow-hidden bg-background px-3 pt-16 text-foreground">
        {children}
      </main>
      <Toaster closeButton richColors  />
    </div>
  );
}
