-- AlterTable
ALTER TABLE "companies" ADD COLUMN     "country" TEXT NOT NULL DEFAULT 'Perú',
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'PEN',
ADD COLUMN     "iso" TEXT NOT NULL DEFAULT 'PE',
ADD COLUMN     "logo" TEXT,
ADD COLUMN     "tax_glose" TEXT NOT NULL DEFAULT 'IGV',
ADD COLUMN     "tax_value" DOUBLE PRECISION NOT NULL DEFAULT 18.00;
