import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { inter } from "@/styles/fonts";

import { AppConstants } from "@/shared/constants/app.constants";
import { ThemeProvider } from "@/providers/theme-provider";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: `${AppConstants.APP_NAME}`,
  description: "Generated by vengardus",
  icons: {
    icon: "/icon.png",
  },
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
