export enum ModuleEnum {
    pos = 'pos',
    config = 'config',
    dashboard = 'dashboard',
    profile = 'profile',
    ai = 'ai',
    aiChat = 'ai-chat',
    aiAgent = 'ai-agent',
    productCategories = 'product-categories',
    products = 'products',
    paymentMethods = 'payment-methods',
    clients = 'clients',
    company = 'company',
    branches = 'branches',
    roles = 'roles',
    users = 'users',
}